name: "dai arcticdem restructuring"
input:
  params:
    - type: "url"
      value: "https://demo.arcticdata.io/tiles/3dtt/PDG/ogdc-dai-test/chunks/tile_index_summary_jump_part_0001.csv"
    - type: "url"
      value: "https://demo.arcticdata.io/tiles/3dtt/PDG/ogdc-dai-test/chunks/tile_index_summary_jump_part_0002.csv"
    - type: "url"
      value: "https://demo.arcticdata.io/tiles/3dtt/PDG/ogdc-dai-test/chunks/tile_index_summary_jump_part_0003.csv"
    - type: "url"
      value: "https://demo.arcticdata.io/tiles/3dtt/PDG/ogdc-dai-test/chunks/tile_index_summary_jump_part_0004.csv"
    - type: "url"
      value: "https://demo.arcticdata.io/tiles/3dtt/PDG/ogdc-dai-test/chunks/tile_index_summary_jump_part_0005.csv"
    - type: "url"
      value: "https://demo.arcticdata.io/tiles/3dtt/PDG/ogdc-dai-test/chunks/tile_index_summary_jump_part_0006.csv"
    - type: "url"
      value: "https://demo.arcticdata.io/tiles/3dtt/PDG/ogdc-dai-test/chunks/tile_index_summary_jump_part_0007.csv"
    - type: "url"
      value: "https://demo.arcticdata.io/tiles/3dtt/PDG/ogdc-dai-test/chunks/tile_index_summary_jump_part_0008.csv"
    - type: "url"
      value: "https://demo.arcticdata.io/tiles/3dtt/PDG/ogdc-dai-test/chunks/tile_index_summary_jump_part_0009.csv"
    - type: "url"
      value: "https://demo.arcticdata.io/tiles/3dtt/PDG/ogdc-dai-test/chunks/tile_index_summary_jump_part_0010.csv"
    - type: "url"
      value: "https://demo.arcticdata.io/tiles/3dtt/PDG/ogdc-dai-test/chunks/tile_index_summary_jump_part_0011.csv"
    - type: "url"
      value: "https://demo.arcticdata.io/tiles/3dtt/PDG/ogdc-dai-test/chunks/tile_index_summary_jump_part_0012.csv"
    - type: "url"
      value: "https://demo.arcticdata.io/tiles/3dtt/PDG/ogdc-dai-test/chunks/tile_index_summary_jump_part_0013.csv"
    - type: "url"
      value: "https://demo.arcticdata.io/tiles/3dtt/PDG/ogdc-dai-test/chunks/tile_index_summary_jump_part_0014.csv"
    - type: "url"
      value: "https://demo.arcticdata.io/tiles/3dtt/PDG/ogdc-dai-test/chunks/tile_index_summary_jump_part_0015.csv"
    - type: "url"
      value: "https://demo.arcticdata.io/tiles/3dtt/PDG/ogdc-dai-test/chunks/tile_index_summary_jump_part_0016.csv"
    - type: "url"
      value: "https://demo.arcticdata.io/tiles/3dtt/PDG/ogdc-dai-test/chunks/tile_index_summary_jump_part_0017.csv"
    - type: "url"
      value: "https://demo.arcticdata.io/tiles/3dtt/PDG/ogdc-dai-test/chunks/tile_index_summary_jump_part_0018.csv"
    - type: "url"
      value: "https://demo.arcticdata.io/tiles/3dtt/PDG/ogdc-dai-test/chunks/tile_index_summary_jump_part_0019.csv"
    - type: "url"
      value: "https://demo.arcticdata.io/tiles/3dtt/PDG/ogdc-dai-test/chunks/tile_index_summary_jump_part_0020.csv"
    - type: "url"
      value: "https://demo.arcticdata.io/tiles/3dtt/PDG/ogdc-dai-test/chunks/tile_index_summary_jump_part_0021.csv"
    - type: "url"
      value: "https://demo.arcticdata.io/tiles/3dtt/PDG/ogdc-dai-test/chunks/tile_index_summary_jump_part_0022.csv"
    - type: "url"
      value: "https://demo.arcticdata.io/tiles/3dtt/PDG/ogdc-dai-test/chunks/tile_index_summary_jump_part_0023.csv"
    - type: "url"
      value: "https://demo.arcticdata.io/tiles/3dtt/PDG/ogdc-dai-test/chunks/tile_index_summary_jump_part_0024.csv"
    - type: "url"
      value: "https://demo.arcticdata.io/tiles/3dtt/PDG/ogdc-dai-test/chunks/tile_index_summary_jump_part_0025.csv"
    - type: "url"
      value: "https://demo.arcticdata.io/tiles/3dtt/PDG/ogdc-dai-test/chunks/tile_index_summary_jump_part_0026.csv"
    - type: "url"
      value: "https://demo.arcticdata.io/tiles/3dtt/PDG/ogdc-dai-test/chunks/tile_index_summary_jump_part_0027.csv"
    - type: "url"
      value: "https://demo.arcticdata.io/tiles/3dtt/PDG/ogdc-dai-test/chunks/tile_index_summary_jump_part_0028.csv"
    - type: "url"
      value: "https://demo.arcticdata.io/tiles/3dtt/PDG/ogdc-dai-test/chunks/tile_index_summary_jump_part_0029.csv"
    - type: "url"
      value: "https://demo.arcticdata.io/tiles/3dtt/PDG/ogdc-dai-test/chunks/tile_index_summary_jump_part_0030.csv"
    - type: "url"
      value: "https://demo.arcticdata.io/tiles/3dtt/PDG/ogdc-dai-test/chunks/tile_index_summary_jump_part_0031.csv"
    - type: "url"
      value: "https://demo.arcticdata.io/tiles/3dtt/PDG/ogdc-dai-test/chunks/tile_index_summary_jump_part_0032.csv"
    - type: "url"
      value: "https://demo.arcticdata.io/tiles/3dtt/PDG/ogdc-dai-test/chunks/tile_index_summary_jump_part_0033.csv"
    - type: "url"
      value: "https://demo.arcticdata.io/tiles/3dtt/PDG/ogdc-dai-test/chunks/tile_index_summary_jump_part_0034.csv"
    - type: "url"
      value: "https://demo.arcticdata.io/tiles/3dtt/PDG/ogdc-dai-test/chunks/tile_index_summary_jump_part_0035.csv"
    - type: "url"
      value: "https://demo.arcticdata.io/tiles/3dtt/PDG/ogdc-dai-test/chunks/tile_index_summary_jump_part_0036.csv"
    - type: "url"
      value: "https://demo.arcticdata.io/tiles/3dtt/PDG/ogdc-dai-test/chunks/tile_index_summary_jump_part_0037.csv"
    - type: "url"
      value: "https://demo.arcticdata.io/tiles/3dtt/PDG/ogdc-dai-test/chunks/tile_index_summary_jump_part_0038.csv"
    - type: "url"
      value: "https://demo.arcticdata.io/tiles/3dtt/PDG/ogdc-dai-test/chunks/tile_index_summary_jump_part_0039.csv"
    - type: "url"
      value: "https://demo.arcticdata.io/tiles/3dtt/PDG/ogdc-dai-test/chunks/tile_index_summary_jump_part_0040.csv"
    - type: "url"
      value: "https://demo.arcticdata.io/tiles/3dtt/PDG/ogdc-dai-test/chunks/tile_index_summary_jump_part_0041.csv"
    - type: "url"
      value: "https://demo.arcticdata.io/tiles/3dtt/PDG/ogdc-dai-test/chunks/tile_index_summary_jump_part_0042.csv"
    - type: "url"
      value: "https://demo.arcticdata.io/tiles/3dtt/PDG/ogdc-dai-test/chunks/tile_index_summary_jump_part_0043.csv"
    - type: "url"
      value: "https://demo.arcticdata.io/tiles/3dtt/PDG/ogdc-dai-test/chunks/tile_index_summary_jump_part_0044.csv"
    - type: "url"
      value: "https://demo.arcticdata.io/tiles/3dtt/PDG/ogdc-dai-test/chunks/tile_index_summary_jump_part_0045.csv"
    - type: "url"
      value: "https://demo.arcticdata.io/tiles/3dtt/PDG/ogdc-dai-test/chunks/tile_index_summary_jump_part_0046.csv"
    - type: "url"
      value: "https://demo.arcticdata.io/tiles/3dtt/PDG/ogdc-dai-test/chunks/tile_index_summary_jump_part_0047.csv"
    - type: "url"
      value: "https://demo.arcticdata.io/tiles/3dtt/PDG/ogdc-dai-test/chunks/tile_index_summary_jump_part_0048.csv"
    - type: "url"
      value: "https://demo.arcticdata.io/tiles/3dtt/PDG/ogdc-dai-test/chunks/tile_index_summary_jump_part_0049.csv"
    - type: "url"
      value: "https://demo.arcticdata.io/tiles/3dtt/PDG/ogdc-dai-test/chunks/tile_index_summary_jump_part_0050.csv"
    - type: "url"
      value: "https://demo.arcticdata.io/tiles/3dtt/PDG/ogdc-dai-test/chunks/tile_index_summary_jump_part_0051.csv"
    - type: "url"
      value: "https://demo.arcticdata.io/tiles/3dtt/PDG/ogdc-dai-test/chunks/tile_index_summary_jump_part_0052.csv"
workflow:
  type: "shell"
  parallel:
    enabled: true
    partition_strategy: "files"
    partition_size: 1
